# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sark/code/cxx/search_engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sark/code/cxx/search_engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sark/code/cxx/search_engine/CMakeFiles /home/sark/code/cxx/search_engine//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sark/code/cxx/search_engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Search-in-files

# Build rule for target.
Search-in-files: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Search-in-files
.PHONY : Search-in-files

# fast build rule for target.
Search-in-files/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Search-in-files.dir/build.make CMakeFiles/Search-in-files.dir/build
.PHONY : Search-in-files/fast

#=============================================================================
# Target rules for targets named Google_tests

# Build rule for target.
Google_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Google_tests
.PHONY : Google_tests

# fast build rule for target.
Google_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_tests.dir/build.make CMakeFiles/Google_tests.dir/build
.PHONY : Google_tests/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f Google_tests/lib/googlemock/CMakeFiles/gmock.dir/build.make Google_tests/lib/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f Google_tests/lib/googlemock/CMakeFiles/gmock_main.dir/build.make Google_tests/lib/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f Google_tests/lib/googletest/CMakeFiles/gtest.dir/build.make Google_tests/lib/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f Google_tests/lib/googletest/CMakeFiles/gtest_main.dir/build.make Google_tests/lib/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

Google_tests/InverterIndexTest.o: Google_tests/InverterIndexTest.cpp.o
.PHONY : Google_tests/InverterIndexTest.o

# target to build an object file
Google_tests/InverterIndexTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_tests.dir/build.make CMakeFiles/Google_tests.dir/Google_tests/InverterIndexTest.cpp.o
.PHONY : Google_tests/InverterIndexTest.cpp.o

Google_tests/InverterIndexTest.i: Google_tests/InverterIndexTest.cpp.i
.PHONY : Google_tests/InverterIndexTest.i

# target to preprocess a source file
Google_tests/InverterIndexTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_tests.dir/build.make CMakeFiles/Google_tests.dir/Google_tests/InverterIndexTest.cpp.i
.PHONY : Google_tests/InverterIndexTest.cpp.i

Google_tests/InverterIndexTest.s: Google_tests/InverterIndexTest.cpp.s
.PHONY : Google_tests/InverterIndexTest.s

# target to generate assembly for a file
Google_tests/InverterIndexTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_tests.dir/build.make CMakeFiles/Google_tests.dir/Google_tests/InverterIndexTest.cpp.s
.PHONY : Google_tests/InverterIndexTest.cpp.s

Google_tests/SearchServerTest.o: Google_tests/SearchServerTest.cpp.o
.PHONY : Google_tests/SearchServerTest.o

# target to build an object file
Google_tests/SearchServerTest.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_tests.dir/build.make CMakeFiles/Google_tests.dir/Google_tests/SearchServerTest.cpp.o
.PHONY : Google_tests/SearchServerTest.cpp.o

Google_tests/SearchServerTest.i: Google_tests/SearchServerTest.cpp.i
.PHONY : Google_tests/SearchServerTest.i

# target to preprocess a source file
Google_tests/SearchServerTest.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_tests.dir/build.make CMakeFiles/Google_tests.dir/Google_tests/SearchServerTest.cpp.i
.PHONY : Google_tests/SearchServerTest.cpp.i

Google_tests/SearchServerTest.s: Google_tests/SearchServerTest.cpp.s
.PHONY : Google_tests/SearchServerTest.s

# target to generate assembly for a file
Google_tests/SearchServerTest.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_tests.dir/build.make CMakeFiles/Google_tests.dir/Google_tests/SearchServerTest.cpp.s
.PHONY : Google_tests/SearchServerTest.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Search-in-files.dir/build.make CMakeFiles/Search-in-files.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Search-in-files.dir/build.make CMakeFiles/Search-in-files.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Search-in-files.dir/build.make CMakeFiles/Search-in-files.dir/main.cpp.s
.PHONY : main.cpp.s

src/ConverterJSON.o: src/ConverterJSON.cpp.o
.PHONY : src/ConverterJSON.o

# target to build an object file
src/ConverterJSON.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Search-in-files.dir/build.make CMakeFiles/Search-in-files.dir/src/ConverterJSON.cpp.o
.PHONY : src/ConverterJSON.cpp.o

src/ConverterJSON.i: src/ConverterJSON.cpp.i
.PHONY : src/ConverterJSON.i

# target to preprocess a source file
src/ConverterJSON.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Search-in-files.dir/build.make CMakeFiles/Search-in-files.dir/src/ConverterJSON.cpp.i
.PHONY : src/ConverterJSON.cpp.i

src/ConverterJSON.s: src/ConverterJSON.cpp.s
.PHONY : src/ConverterJSON.s

# target to generate assembly for a file
src/ConverterJSON.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Search-in-files.dir/build.make CMakeFiles/Search-in-files.dir/src/ConverterJSON.cpp.s
.PHONY : src/ConverterJSON.cpp.s

src/InvertedIndex.o: src/InvertedIndex.cpp.o
.PHONY : src/InvertedIndex.o

# target to build an object file
src/InvertedIndex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Search-in-files.dir/build.make CMakeFiles/Search-in-files.dir/src/InvertedIndex.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_tests.dir/build.make CMakeFiles/Google_tests.dir/src/InvertedIndex.cpp.o
.PHONY : src/InvertedIndex.cpp.o

src/InvertedIndex.i: src/InvertedIndex.cpp.i
.PHONY : src/InvertedIndex.i

# target to preprocess a source file
src/InvertedIndex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Search-in-files.dir/build.make CMakeFiles/Search-in-files.dir/src/InvertedIndex.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_tests.dir/build.make CMakeFiles/Google_tests.dir/src/InvertedIndex.cpp.i
.PHONY : src/InvertedIndex.cpp.i

src/InvertedIndex.s: src/InvertedIndex.cpp.s
.PHONY : src/InvertedIndex.s

# target to generate assembly for a file
src/InvertedIndex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Search-in-files.dir/build.make CMakeFiles/Search-in-files.dir/src/InvertedIndex.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_tests.dir/build.make CMakeFiles/Google_tests.dir/src/InvertedIndex.cpp.s
.PHONY : src/InvertedIndex.cpp.s

src/SearchServer.o: src/SearchServer.cpp.o
.PHONY : src/SearchServer.o

# target to build an object file
src/SearchServer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Search-in-files.dir/build.make CMakeFiles/Search-in-files.dir/src/SearchServer.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_tests.dir/build.make CMakeFiles/Google_tests.dir/src/SearchServer.cpp.o
.PHONY : src/SearchServer.cpp.o

src/SearchServer.i: src/SearchServer.cpp.i
.PHONY : src/SearchServer.i

# target to preprocess a source file
src/SearchServer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Search-in-files.dir/build.make CMakeFiles/Search-in-files.dir/src/SearchServer.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_tests.dir/build.make CMakeFiles/Google_tests.dir/src/SearchServer.cpp.i
.PHONY : src/SearchServer.cpp.i

src/SearchServer.s: src/SearchServer.cpp.s
.PHONY : src/SearchServer.s

# target to generate assembly for a file
src/SearchServer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Search-in-files.dir/build.make CMakeFiles/Search-in-files.dir/src/SearchServer.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Google_tests.dir/build.make CMakeFiles/Google_tests.dir/src/SearchServer.cpp.s
.PHONY : src/SearchServer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... Google_tests"
	@echo "... Search-in-files"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... Google_tests/InverterIndexTest.o"
	@echo "... Google_tests/InverterIndexTest.i"
	@echo "... Google_tests/InverterIndexTest.s"
	@echo "... Google_tests/SearchServerTest.o"
	@echo "... Google_tests/SearchServerTest.i"
	@echo "... Google_tests/SearchServerTest.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/ConverterJSON.o"
	@echo "... src/ConverterJSON.i"
	@echo "... src/ConverterJSON.s"
	@echo "... src/InvertedIndex.o"
	@echo "... src/InvertedIndex.i"
	@echo "... src/InvertedIndex.s"
	@echo "... src/SearchServer.o"
	@echo "... src/SearchServer.i"
	@echo "... src/SearchServer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

